name: Build binaries on release

on:
  release:
    types: ['published']

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly

      - name: Install system dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev

      - name: Build VST3 bundle for Linux
        run: cargo run --package xtask --release bundle microdelay
      
      - uses: softprops/action-gh-release@v2
        with:
          files:
            ./target/bundled/microdelay.vst3/Contents/x86_64-linux/microdelay.so

  build-windows:
    name: Build for Windows (MSVC)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly

      - name: Build VST3 for Windows
        run: cargo run --package xtask --release bundle microdelay
      
      - uses: softprops/action-gh-release@v2
        with:
          files:
            D:/a/micro_delay_vst3/micro_delay_vst3/target/bundled/microdelay.vst3